<a href="https://colab.research.google.com/github/Yyyyyjkim/Molecule_analysis/blob/main/02_descriptors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# deepchem

In [ ]:
!pip install deepchem

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting deepchem
  Downloading deepchem-2.6.1-py3-none-any.whl (608 kB)
     |████████████████████████████████| 608 kB 5.0 MB/s
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from deepchem) (1.3.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from deepchem) (1.4.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from deepchem) (1.1.0)
Collecting rdkit-pypi
  Downloading rdkit_pypi-2022.3.4-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (22.7 MB)
     |████████████████████████████████| 22.7 MB 70.3 MB/s
Requirement already satisfied: numpy>=1.21 in /usr/local/lib/python3.7/dist-packages (from deepchem) (1.21.6)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from deepchem) (1.0.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->deepchem) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->deepchem) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->deepchem) (1.15.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.7/dist-packages (from rdkit-pypi->deepchem) (7.1.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->deepchem) (3.1.0)
Installing collected packages: rdkit-pypi, deepchem
Successfully installed deepchem-2.6.1 rdkit-pypi-2022.3.4

In [ ]:
!pip install mordred

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting mordred
  Downloading mordred-1.2.0.tar.gz (128 kB)
     |████████████████████████████████| 128 kB 5.7 MB/s
Requirement already satisfied: six==1.* in /usr/local/lib/python3.7/dist-packages (from mordred) (1.15.0)
Requirement already satisfied: numpy==1.* in /usr/local/lib/python3.7/dist-packages (from mordred) (1.21.6)
Requirement already satisfied: networkx==2.* in /usr/local/lib/python3.7/dist-packages (from mordred) (2.6.3)
Building wheels for collected packages: mordred
  Building wheel for mordred (setup.py) ... done
  Created wheel for mordred: filename=mordred-1.2.0-py3-none-any.whl size=176725 sha256=15cebd5daf44d317ccb56119faa8cd9316cd715216ecc7fea435f76dce12a766
  Stored in directory: /root/.cache/pip/wheels/02/c0/2e/e7e3d63b431777712ebc128bc4deb9ac5cb19afc7c1ea341ec
Successfully built mordred
Installing collected packages: mordred
Successfully installed mordred-1.2.0

In [ ]:
import deepchem as dc
from rdkit import Chem
import pandas as pd

- RDKIT descriptors

In [ ]:
mol = Chem.MolFromSmiles('CCC')
featurizer = dc.feat.RDKitDescriptors()
rdkit_mol = featurizer.featurize(mol)
desc_rdkit = [i[0] for i in featurizer.descList]

In [ ]:
pd.DataFrame(rdkit_mol, columns=desc_rdkit)

,MaxEStateIndex,MinEStateIndex,MaxAbsEStateIndex,MinAbsEStateIndex,qed,MolWt,HeavyAtomMolWt,ExactMolWt,NumValenceElectrons,NumRadicalElectrons,...,fr_sulfide,fr_sulfonamd,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea
0,2.125,1.25,2.125,1.25,0.385471,44.097,36.033,44.0626,20.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

- circular fingerprint

In [ ]:
mol = Chem.MolFromSmiles('CCC')
featurizer = dc.feat.CircularFingerprint(size=1024)
desc_mol = featurizer.featurize(mol)
desc_circular = [f"circular_{i}" for i in range(desc_mol.shape[1])]

In [ ]:
pd.DataFrame(desc_mol, columns=desc_circular)

,circular_0,circular_1,circular_2,circular_3,circular_4,circular_5,circular_6,circular_7,circular_8,circular_9,...,circular_1014,circular_1015,circular_1016,circular_1017,circular_1018,circular_1019,circular_1020,circular_1021,circular_1022,circular_1023
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

- MACCS

In [ ]:
mol = Chem.MolFromSmiles('CCC')
featurizer = dc.feat.MACCSKeysFingerprint()
desc_mol = featurizer.featurize(mol)
desc_maccs = [f"maccs_{i}" for i in range(desc_mol.shape[1])]

In [ ]:
pd.DataFrame(desc_mol, columns=desc_maccs)

,maccs_0,maccs_1,maccs_2,maccs_3,maccs_4,maccs_5,maccs_6,maccs_7,maccs_8,maccs_9,...,maccs_157,maccs_158,maccs_159,maccs_160,maccs_161,maccs_162,maccs_163,maccs_164,maccs_165,maccs_166
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

- mordred

In [ ]:
mol = Chem.MolFromSmiles('CCC')
featurizer = dc.feat.MordredDescriptors(ignore_3D=False)
desc_mol = featurizer.featurize(mol)
desc_mordred = [f"mordred_{i}" for i in range(desc_mol.shape[1])]

In [ ]:
pd.DataFrame(desc_mol, columns=desc_mordred)

,mordred_0,mordred_1,mordred_2,mordred_3,mordred_4,mordred_5,mordred_6,mordred_7,mordred_8,mordred_9,...,mordred_1816,mordred_1817,mordred_1818,mordred_1819,mordred_1820,mordred_1821,mordred_1822,mordred_1823,mordred_1824,mordred_1825
0,1.414214,1.414214,0.0,0.0,2.828427,1.414214,2.828427,2.828427,0.942809,1.849457,...,4.174387,17.310771,44.0626,4.005691,4.0,0.0,6.0,4.0,2.25,1.0

# Mordred

In [ ]:
from mordred import Calculator, descriptors

In [ ]:
calc = Calculator(descriptors)

mol = Chem.MolFromSmiles('CCC')
desc_mol = calc(mol)

desc_mordred = desc_mol.asdict().keys()
desc_mol = desc_mol.asdict().values()

In [ ]:
pd.DataFrame([desc_mol], columns=desc_mordred)

,ABC,ABCGG,nAcid,nBase,SpAbs_A,SpMax_A,SpDiam_A,SpAD_A,SpMAD_A,LogEE_A,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,1.414214,1.414214,0,0,2.828427,1.414214,2.828427,2.828427,0.942809,1.849457,...,4.174387,17.310771,44.0626,4.005691,4,0,6.0,4.0,2.25,1.0

# padelpy

In [ ]:
!pip install padelpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting padelpy
  Downloading padelpy-0.1.11-py2.py3-none-any.whl (20.9 MB)
     |████████████████████████████████| 20.9 MB 1.4 MB/s
Installing collected packages: padelpy
Successfully installed padelpy-0.1.11

In [ ]:
from padelpy import from_smiles

In [ ]:
descriptors = from_smiles('CCC', timeout=100)
desc_padel = list(descriptors.keys())
desc_mol = list(descriptors.values())

In [ ]:
pd.DataFrame([desc_mol], columns=desc_padel)

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,nHeavyAtom,nH,...,P1s,P2s,E1s,E2s,E3s,Ts,As,Vs,Ks,Ds
0,0,-0.1853999999999998,0.034373159999999923,14.709,10.614344000000001,0,0,11,3,8,...,0.6017665070277322,0.23564928690016262,0.5826832645958444,0.4054181794909671,0.5279457968416315,2.7485662270798525,2.0998541800945647,5.327150925703745,0.4026497605415983,1.516047240928443

# pybiomed

In [ ]:
!pip install openbabel_wheel

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting openbabel_wheel
  Downloading openbabel_wheel-3.1.1.7-cp37-cp37m-manylinux_2_24_x86_64.whl (23.8 MB)
     |████████████████████████████████| 23.8 MB 74.1 MB/s
Installing collected packages: openbabel-wheel
Successfully installed openbabel-wheel-3.1.1.7

In [ ]:
!git clone https://github.com/gadsbyfly/PyBioMed.git

Cloning into 'PyBioMed'...
remote: Enumerating objects: 1371, done.
remote: Counting objects: 100% (350/350), done.
remote: Compressing objects: 100% (233/233), done.
remote: Total 1371 (delta 208), reused 183 (delta 117), pack-reused 1021
Receiving objects: 100% (1371/1371), 49.91 MiB | 36.27 MiB/s, done.
Resolving deltas: 100% (828/828), done.

In [ ]:
import os
os.chdir('./PyBioMed/')

In [ ]:
from PyBioMed import Pymolecule

In [ ]:
mol = Pymolecule.PyMolecule()
mol.ReadMolFromSmile('CCC')

In [ ]:
mol_charge = mol.GetCharge()
mol_con = mol.GetConnectivity()
mol_const = mol.GetConstitution()
mol_basak = mol.GetBasak()
mol_burden = mol.GetBurden()
mol_estate = mol.GetEstate()
mol_geary = mol.GetGeary()
mol_moe  = mol.GetMOE()
mol_molp = mol.GetMolProperty()
mol_moran = mol.GetMoran()
mol_mb = mol.GetMoreauBroto()
mol_cats = mol.GetCATS2D()

# 아래 두개는 error
# mol_kappa = mol.GetKappa()
# mol_top = mol.GetTopology()

In [ ]:
prop_list = ['charge', 'con', 'const', 'basak', 'burden', 'estate', 'geary', 'moe', 'molp', 'moran', 'mb', 'cats']

desc_mol = []
desc_biomed = []

for _, prop in enumerate(prop_list):

    desc_biomed.append(list(globals()[f"mol_{prop}"].keys()))
    desc_mol.append(list(globals()[f"mol_{prop}"].values()))

desc_biomed = sum(desc_biomed, [])
desc_mol = sum(desc_mol, [])

In [ ]:
pd.DataFrame([desc_mol], columns=desc_biomed)

,SPP,LDI,Rnc,Rpc,Mac,Tac,Mnc,Tnc,Mpc,Tpc,...,CATS_LL0,CATS_LL1,CATS_LL2,CATS_LL3,CATS_LL4,CATS_LL5,CATS_LL6,CATS_LL7,CATS_LL8,CATS_LL9
0,0.092,0.007,0.345,0.137,0.035,0.381,-0.063,-0.19,0.024,0.19,...,0.5,0.333,0.167,0.0,0.0,0.0,0.0,0.0,0.0,0.0